from __future__ import annotations

import streamlit as st

from core.pos_recon.bank_loader import load_json_to_workbook
from core.memory import get_memory_usage_mb
from utils.audit_viewer import render_audit_table
from utils.ui_components import (
    render_download_button,
    render_header,
    render_memory_badge,
    render_metric_cards,
)

st.set_page_config(
    page_title="Bank Statement Loader | POS Automation",
    page_icon="🏦",
    layout="wide",
)

render_memory_badge()

render_header(
    title="Bank Statement POS Loader",
    subtitle="Load Chrome extension POS JSON export into the BANK STATEMENT column with error annotations",
    icon="🏦",
)

st.markdown(
    """
    Upload your **Reconciliation Workbook** and the **JSON export** generated by the Moniepoint POS Chrome extension. 
    The engine maps credit amounts into the `BANK STATEMENT` column and annotates non-OK/failed records with cell comments.
    """
)

with st.form("bank_loader_form"):
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("1. Reconciliation Workbook & JSON Export")
        workbook_file = st.file_uploader(
            "Upload Reconciliation Workbook (.xlsx / .xlsm)",
            type=["xlsx", "xlsm"],
            help="Excel workbook containing BANK STATEMENT columns.",
        )
        json_file = st.file_uploader(
            "Upload Chrome Extension JSON Export (.json)",
            type=["json"],
            help="The JSON export file from the Chrome extension.",
        )

    with col2:
        st.subheader("2. Loading Parameters")
        date_input = st.text_input(
            "Target Report Date (YYYY-MM-DD)",
            value="",
            placeholder="e.g. 2026-09-19 (leave blank to infer from JSON)",
            help="Selects the matching report block. If blank, infers date from JSON metadata.",
        )
        block_number = st.number_input(
            "Report Block Number",
            min_value=1,
            value=1,
            help="1-based report block number if date is omitted and multiple blocks exist.",
        )
        failed_text = st.text_input(
            "Text for Failed / Non-OK Records",
            value="FAILED",
            help="Value written into the cell for failed records (error details are added as comments).",
        )

    submit_button = st.form_submit_button("💳 Populate Bank Statement Column", type="primary", use_container_width=True)

if submit_button:
    if not workbook_file:
        st.error("Please upload the Reconciliation Workbook.")
    elif not json_file:
        st.error("Please upload the POS Extension JSON export.")
    else:
        date_clean = date_input.strip() or None

        try:
            with st.spinner("Mapping POS records and populating BANK STATEMENT column..."):
                output_path, stats = load_json_to_workbook(
                    workbook_input=workbook_file,
                    json_input=json_file,
                    date=date_clean,
                    block_number=int(block_number),
                    failed_text=failed_text.strip() or "FAILED",
                )

            st.success(f"Bank statement populated successfully for Report Date: **{stats['workbookDate'] or 'N/A'}**.")

            # Summary Metrics
            render_metric_cards([
                ("JSON Records", stats["jsonRecords"], None),
                ("Matched Rows", stats["matched"], None),
                ("OK Written", stats["okWritten"], None),
                ("Failed / Status Written", stats["statusWritten"], None),
            ])

            # Download Action
            st.markdown("### 📥 Download Updated Workbook")
            render_download_button(
                file_path=output_path,
                label="📥 Download Filled Reconciliation Workbook (.xlsx)",
                download_filename=f"{workbook_file.name.rsplit('.', 1)[0]}_bank_loaded_{stats['workbookDate'].replace('-', '') if stats['workbookDate'] else 'updated'}.xlsx",
            )

            # Details
            if stats.get("mappingDetails"):
                render_audit_table(stats["mappingDetails"], title="Terminal Mapping Status Preview")

        except Exception as exc:
            st.error(f"Loader Error: {exc}")
