[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 500

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0284c7"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"
font = "sans serif"
